### ISSUE TITLE
Error: undeclared identifier: 'Context'

### ISSUE THREAD

**Issue by idwaker** [StefanSalewski/nim-gdk3#1]
Tried to compile test.nim from nim-gtk3 package on my Archlinux with

nim 0.10.2-1
nimble 1:0.6-1
gtk3 3.14.8-1
gcc 4.9.2-3

and got this error

    /home/idwaker/.nimble/pkgs/cairo-1.0/cairo.nim(731, 23) Warning: use AssertionError instead;   EAssertionFailed is deprecated [Deprecated]
    /home/idwaker/.nimble/pkgs/cairo-1.0/cairo.nim(724, 20) Warning: 'nil' statement is deprecated; use an empty 'discard' statement instead [NilStmt]
    /home/idwaker/.nimble/pkgs/gdk3-3.15.3/gdk3.nim(21, 18) Error: undeclared identifier: 'Context'

**Comment by StefanSalewski** [comment]
Thanks for your report. Today I will add modules GIO and ATK -- if you are still interested, please download all my modules  (10) and try again.
