### ISSUE TITLE
OS X Quartz Library name

### ISSUE THREAD

**Issue by oderwat** [StefanSalewski/nim-gdk3#3]
I mentioned this for nim-gtk3 already. I installed gtk+3 with homebrew on my mac (--without-x11) and this created `libgdk-3.0.dylib` instead of `libgdk-quartz-3.0.dylib`.

**Comment by StefanSalewski** [comment]
Sorry, I have no idea about library names for Windows and Mac. It was only a guess.

**Comment by oderwat** [comment]
No problem. I guess the names could be different with other ways to install GTK+3. If your version was a guess it probably is the standard as I found it. Time will tell :)
