### ISSUE TITLE
gdk3.nim(24, 19) Error: undeclared identifier: 'Context'

### ISSUE THREAD

**Issue by ephja** [StefanSalewski/nim-gdk3#4]
That's because I didn't have cairo apparently. I've installed all the relevant libraries but now I get this ```gdk3.nim(26, 19) Error: undeclared identifier: 'LayoutLine'```

**Comment by StefanSalewski** [comment]
On Wed, 2016-01-20 at 10:37 -0800, ephja wrote:
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/StefanSalewski/nim-gdk3/issues/4

grep LayoutLine *.nim
gdk3.nim:from pango import LayoutLine, Layout, Context, Direction

I told you you need all the modules from my github page, sorry.

The missing is pango.

PS: I got an empty email text from you, but read your comment at github
page. Strange.

**Comment by ephja** [comment]
By "all the relevant libraries" I meant pango as well.

**Comment by StefanSalewski** [comment]
On Wed, 2016-01-20 at 11:02 -0800, ephja wrote:
> By "all the relevant libraries" I meant pango as well.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/StefanSalewski/nim-gdk3/issues/4#issuecomment-1733
> 25705

You need the C library and the Nim wrapper both: The C pango library is
for my linux box

/usr/lib64/libpango-1.0.so

But you need also the Nim wrapper file:

pango.nim

For my current project I created links from my working directory to the
directories with *.nim files. That is

pango.nim -> /home/stefan/nim-pango/src/pango.nim

and similar to the 10 other wrappers.

I have just checked at github, pango.nim:

type
LayoutLine* =  ptr LayoutLineObj

So it is exported. So it should work fine. Have used it with Nim 0.12
and Nim 0.13

Are you on Windows? Should not really make a difference, but I can not
test that.

Have you some basic experience with Nim? Generally it is very easy to
find out what symbols are missing. Maybe you have an old pango.nim
shipped with old Nimrod?

**Comment by ephja** [comment]
It was using the pango module from the gtk2 package.
